### ISSUE TITLE
getfromsolr

### ISSUE THREAD

**Issue by GoogleCodeExporter** [solrmarc/solrmarc#17]
```
What steps will reproduce the problem?
1.
../dist/getfromsolr http://localhost:8080/apache-solr-1.4-dev id:5637241

The index contains a record with that ID.

What is the expected output? What do you see instead?
I was hoping to get a marc record out of the solr index. But instead I get:
Unable to find a $JAVA_HOME at "/usr", continuing with system-provided Java...
Exception in thread "main" java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.jav
a:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.simontuffs.onejar.Boot.run(Boot.java:320)
    at com.simontuffs.onejar.Boot.main(Boot.java:161)
Caused by: java.lang.NullPointerException
    at org.solrmarc.solr.RemoteSolrSearcher.handleAll(RemoteSolrSearcher.java:73)
    at org.solrmarc.solr.RemoteSolrSearcher.main(RemoteSolrSearcher.java:414)
    ... 6 more


What version of the product are you using? On what operating system?
Max OSX 10.6, solrmarc built from trunk



```

Original issue reported on code.google.com by `willem.v...@gmail.com` on 10 Nov 2009 at 11:44

**Comment by haschart** [comment]
Keeping this issue as a place holder.  The new version no longer provides this functionality. It should.
