### ISSUE TITLE
Error: Problem instantiating SolrCore

### ISSUE THREAD

**Issue by GoogleCodeExporter** [solrmarc/solrmarc#28]
```
What steps will reproduce the problem?
1. Untar the the bin release, setup the config file and run:
# bin/indexfile ./myprefix_config.properties my.mrc

What is the expected output? What do you see instead?
I expect to see the mrc file being indexed.

Instead I see:
Mar 18, 2013 8:33:55 PM org.solrmarc.marc.MarcImporter main
INFO: Starting SolrMarc indexing.
Mar 18, 2013 8:33:55 PM org.solrmarc.tools.Utils getPropertyFileAbsoluteURL
INFO: Opening file: /root/solr/solrmarc/./myprefix_config.properties
Mar 18, 2013 8:33:55 PM org.solrmarc.marc.MarcImporter getSolrServerProxy
INFO:  Updating to Solr index at /opt/apache-solr-3.6.2/sm/solr
Mar 18, 2013 8:33:55 PM org.solrmarc.solr.SolrCoreLoader loadEmbeddedCore
INFO: Using the multicore schema file at : 
/opt/apache-solr-3.6.2/sm/solr/solr.xml
Mar 18, 2013 8:33:55 PM org.solrmarc.solr.SolrCoreLoader loadEmbeddedCore
INFO: Using the null core
Mar 18, 2013 8:33:55 PM org.solrmarc.solr.SolrCoreLoader loadEmbeddedCore
INFO: Using the data directory of: /opt/apache-solr-3.6.2/sm/solr/null
Error: Problem instantiating SolrCore
Mar 18, 2013 8:33:56 PM org.solrmarc.solr.SolrCoreLoader loadEmbeddedCore
SEVERE: Error: Problem instantiating SolrCore
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.solrmarc.solr.SolrCoreLoader.loadEmbeddedCore(SolrCoreLoader.java:235)
        at org.solrmarc.marc.MarcImporter.getSolrServerProxy(MarcImporter.java:839)
        at org.solrmarc.marc.MarcImporter.loadLocalProperties(MarcImporter.java:202)
        at org.solrmarc.marc.MarcHandler.loadProperties(MarcHandler.java:171)
        at org.solrmarc.marc.MarcHandler.init(MarcHandler.java:119)
        at org.solrmarc.marc.MarcImporter.main(MarcImporter.java:857)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at com.simontuffs.onejar.Boot.run(Boot.java:334)
        at com.simontuffs.onejar.Boot.main(Boot.java:170)
Caused by: java.lang.NullPointerException
        at org.apache.solr.core.CoreContainer.checkDefault(CoreContainer.java:550)
        at org.apache.solr.core.CoreContainer.getCore(CoreContainer.java:600)
        ... 16 more


What version of the product are you using? On what operating system?
SolrMarc Version: SolrMarc_Generic_Binary_Unix-2.5.1.tar.gz
Linux distro: CentOS release 6.3 (Final)
Solr: 3.6.2
java version "1.7.0_15"

Anybody have any ideas why I'm having problems here?

Thanks.


```

Original issue reported on code.google.com by `sleeper0...@gmail.com` on 19 Mar 2013 at 2:47

**Comment by haschart** [comment]
Issue from previous version, no longer relevant
