### ISSUE TITLE
Indexing failed because of problem instantiating SolrCore

### ISSUE THREAD

**Issue by GoogleCodeExporter** [solrmarc/solrmarc#30]
```
What steps will reproduce the problem?
1. setting up schema.xml, solr.xml, config.properties (see appendix) and 
index.properties (with certain indexing scripts)
2. starting Solr-machine
3. building new core named gbv
4. running indexfile with certain mrc: ./indexfile file.mrc

What is the expected output? What do you see instead?
Expected to see that the mrc-file beeing indexed.

instead the log says:
 INFO [main] (MarcImporter.java:849) - Starting SolrMarc indexing.
 INFO [main] (Utils.java:339) - Opening file: /home/fichte/Downloads/solrMarcSource/config.properties
 INFO [main] (MarcImporter.java:819) -  Updating to Solr index at /home/fichte/Downloads/solr/solr-4.8.1/example/solr
 INFO [main] (MarcImporter.java:832) -      Using Solr data dir /home/fichte/Downloads/solr/solr-4.8.1/example/solr/gbv/data
 INFO [main] (MarcImporter.java:835) -      Using Solr core gbv
 INFO [main] (SolrCoreLoader.java:219) - Using the multicore schema file at : /home/fichte/Downloads/solr/solr-4.8.1/example/solr/solr.xml
 INFO [main] (SolrCoreLoader.java:220) - Using the gbv core
 INFO [main] (SolrCoreLoader.java:227) - Using the data directory of: /home/fichte/Downloads/solr/solr-4.8.1/example/solr/gbv/data
Error: Problem instantiating SolrCore
ERROR [main] (SolrCoreLoader.java:346) - Error: Problem instantiating SolrCore
java.lang.NoSuchMethodException: 
org.apache.solr.core.CoreContainer.<init>(java.lang.String, java.io.File)
    at java.lang.Class.getConstructor0(Class.java:2971)
    at java.lang.Class.getConstructor(Class.java:1812)
    at org.solrmarc.solr.SolrCoreLoader.loadEmbeddedCore(SolrCoreLoader.java:230)
    at org.solrmarc.marc.MarcImporter.getSolrServerProxy(MarcImporter.java:837)
    at org.solrmarc.marc.MarcImporter.loadLocalProperties(MarcImporter.java:201)
    at org.solrmarc.marc.MarcHandler.loadProperties(MarcHandler.java:171)
    at org.solrmarc.marc.MarcHandler.init(MarcHandler.java:119)
    at org.solrmarc.marc.MarcImporter.main(MarcImporter.java:855)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.simontuffs.onejar.Boot.run(Boot.java:334)
    at com.simontuffs.onejar.Boot.main(Boot.java:170)


What version of the product are you using? On what operating system?
SolrMarc: SolrMarc_Generic_Binary_Unix-2.6.tar.gz
Solr: 4.8
OS: Ubuntu 12.04
Java: Sun 1.8.0_11-b12


Please provide any additional information below.
Note: If I use "solr.path = REMOTE" instead of "solr.path = path/to/solr" in 
config.properties, everything works fine by using the remote interface and the 
file will be indexed - but its much slower than pushing the index directly into 
the directory. I guess the exception has something to do with the line 
"Constructor<?> coreContainerConstructor = 
coreContainerClass.getConstructor(String.class, File.class);" found in the 
method loadEmbeddedCore in class SolrCoreLoader but I can not help. 

Any suggestions or ideas?
Thanks.

```

Original issue reported on code.google.com by `lorenz.f...@googlemail.com` on 14 Aug 2014 at 12:57

Attachments:
- [solr.xml](https://storage.googleapis.com/google-code-attachments/solrmarc/issue-30/comment-0/solr.xml)
- [config.properties](https://storage.googleapis.com/google-code-attachments/solrmarc/issue-30/comment-0/config.properties)

**Comment by haschart** [comment]
Direct writing to a Solr index is no longer supported by the new version so this issue is no longer relevant.
