### ISSUE TITLE
can't indexing MARC with Solr 5.2.1

### ISSUE THREAD

**Issue by GoogleCodeExporter** [solrmarc/solrmarc#31]
```
Hi,

I can index MARC file using 
SolrMarc_Generic_Binary_PC-2.6\jetty\webapps\solr.war

But, when I use Solr 5.2.1 , I am getting this error:

INFO [main] (MarcImporter.java:851) - Starting SolrMarc indexing.
 INFO [main] (Utils.java:339) - Opening file: C:\indexer\myprefix_config.propert
ies
 INFO [main] (MarcImporter.java:821) -  Updating to Solr index at C:\indexer\ser
ver\solr
 INFO [main] (MarcImporter.java:834) -      Using Solr data dir server/solr/Adve
ntureWK/data
 INFO [main] (MarcImporter.java:837) -      Using Solr core AdventureWK
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.simontuffs.onejar.Boot.run(Boot.java:334)
        at com.simontuffs.onejar.Boot.main(Boot.java:170)
Caused by: java.lang.VerifyError: class org.apache.solr.client.solrj.impl.Common
sHttpSolrServer overrides final method request.(Lorg/apache/solr/client/solrj/So
lrRequest;)Lorg/apache/solr/common/util/NamedList;
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at com.simontuffs.onejar.JarClassLoader.defineClass(JarClassLoader.java:
1037)
        at com.simontuffs.onejar.JarClassLoader.findClass(JarClassLoader.java:94
3)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at com.simontuffs.onejar.JarClassLoader.defineClass(JarClassLoader.java:
1037)
        at com.simontuffs.onejar.JarClassLoader.findClass(JarClassLoader.java:94
3)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.solrmarc.marc.MarcImporter.getSolrServerProxy(MarcImporter.java:8
39)
        at org.solrmarc.marc.MarcImporter.loadLocalProperties(MarcImporter.java:
202)
        at org.solrmarc.marc.MarcHandler.loadProperties(MarcHandler.java:171)
        at org.solrmarc.marc.MarcHandler.init(MarcHandler.java:119)
        at org.solrmarc.marc.MarcImporter.main(MarcImporter.java:857)
        ... 6 more


What version of the product are you using? On what operating system?
Windows 8.1 , Solr 5.2.1

Thanks,
Thida

```

Original issue reported on code.google.com by `FridayJ...@gmail.com` on 30 Jul 2015 at 10:23

**Comment by haschart** [comment]
Direct writing to a Solr index is no longer supported by the new version so this issue is no longer relevant.
