### ISSUE TITLE
No class found when running solrmarc_core_3.1

### ISSUE THREAD

**Issue by pierbin** [solrmarc/solrmarc#80]
Hi,

I tried to run the Solrmarc in windows 10, and I ran into the below issue. The lib sub-dir and the solrmarc_core_3.1.jar are in the same dir. Any ideas about it? Thanks.
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/log4j/Logger
        at org.solrmarc.driver.Boot.addLibDirJarstoClassPath(Boot.java:242)
        at org.solrmarc.driver.Boot.<clinit>(Boot.java:32)

**Comment by haschart** [comment]
What version of Java are you using?    Changes made as a part of Java 9 and Java 10 cause the method of dynamic classloading used by solrmarc to fail.     There is now newer code checked in that attempt to address this issue, but there hasn't yet been a release made that incorporates those changes.

**Comment by pierbin** [comment]
Hi there,

Thank you for your reply. I've figured it out. Yes, that's the Java version
problem.

Best Regards,
Pier
