### ISSUE TITLE
JDK11 + symbolic links = trouble

### ISSUE THREAD

**Issue by demiankatz** [solrmarc/solrmarc#87]
It seems that if your SolrMarc directory is symbolically linked, it causes problems when running under JDK11 (JDK8 works fine). Here are some steps that can be easily used to reproduce the problem:

<pre>
mkdir /tmp/vufind
cd /tmp/vufind
git clone https://github.com/vufind-org/vufind.git .
composer install
php install.php --non-interactive
export VUFIND_HOME=`pwd`
export VUFIND_LOCAL_DIR=$VUFIND_HOME/local
./solr.sh start
mv import foo
ln -s foo import
./import-marc.sh tests/data/journals.mrc
</pre>

This results in the output:

<pre>
Now Importing tests/data/journals.mrc ...
Oct 28, 16:50:21 java -Xms512m -Xmx512m -DentityExpansionLimit=0 -Duser.timezone=UTC  -jar /tmp/vufind/import/solrmarc_core_3.3.jar /tmp/vufind/local/import/import.properties -solrj /tmp/vufind/solr/vendor/dist/solrj-lib /tmp/vufind/tests/data/journals.mrc
log4j:WARN No appenders could be found for logger (org.solrmarc.driver.IndexDriver).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
DEBUG [main] (BootableMain.java:117) - Adding directory: /tmp/vufind/local/import
DEBUG [main] (BootableMain.java:117) - Adding directory: /tmp/vufind/import
DEBUG [main] (Boot.java:638) - Number of homeDirStrs: 3
DEBUG [main] (Boot.java:641) - homeDirStrs[0]: /tmp/vufind/local/import
DEBUG [main] (Boot.java:645) - homeDirStrs[1]: /tmp/vufind/import
DEBUG [main] (Boot.java:650) - Checking for jars files in directory: /tmp/vufind/foo/lib_local
DEBUG [main] (Boot.java:654) - Adding jars files in directory: /tmp/vufind/foo/lib_local
DEBUG [main] (Boot.java:650) - Checking for jars files in directory: /tmp/vufind/import/lib_local
DEBUG [main] (Boot.java:654) - Adding jars files in directory: /tmp/vufind/import/lib_local
DEBUG [main] (Boot.java:650) - Checking for jars files in directory: /tmp/vufind/local/import/lib_local
 INFO [main] (ValueIndexerFactory.java:118) - Using directory: /tmp/vufind/import/index_java as location of java sources
 INFO [main] (ValueIndexerFactory.java:118) - Using directory: /tmp/vufind/foo/index_java as location of java sources
 INFO [main] (PropertyUtils.java:313) - Opening file (instead of 1 other options): /tmp/vufind/import/vufind.properties
 INFO [main] (PropertyUtils.java:313) - Opening file (instead of 1 other options): /tmp/vufind/import/vufind.properties
FATAL [main] (Boot.java:212) - ERROR: Error while invoking main method in specified class: org.solrmarc.driver.IndexDriver
java.lang.LinkageError: loader org.solrmarc.driver.Boot @4617c264 attempted duplicate interface definition for org.ini4j.Persistable. (org.ini4j.Persistable is in unnamed module of loader org.solrmarc.driver.Boot @4617c264, parent loader 'app')
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:877)
        at org.solrmarc.driver.Boot.loadClass(Boot.java:141)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:877)
        at org.solrmarc.driver.Boot.loadClass(Boot.java:141)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:575)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
        at java.base/java.lang.Class.getDeclaredMethods(Class.java:2309)
        at org.solrmarc.index.extractor.methodcall.MethodCallManager.add(MethodCallManager.java:115)
        at org.solrmarc.index.extractor.methodcall.MethodCallManager.add(MethodCallManager.java:106)
        at org.solrmarc.index.extractor.methodcall.AbstractMethodCallFactory.addMethodsFromClasses(AbstractMethodCallFactory.java:36)
        at org.solrmarc.index.extractor.impl.java.JavaValueExtractorFactory.<init>(JavaValueExtractorFactory.java:16)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.lang.Class.newInstance(Class.java:584)
        at org.solrmarc.index.indexer.ValueIndexerFactory.createExtractorFactories(ValueIndexerFactory.java:522)
        at org.solrmarc.index.indexer.ValueIndexerFactory.initialize(ValueIndexerFactory.java:80)
        at org.solrmarc.driver.IndexDriver.execute(IndexDriver.java:92)
        at org.solrmarc.driver.IndexDriver.main(IndexDriver.java:69)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.solrmarc.driver.Boot.invokeMain(Boot.java:201)
        at org.solrmarc.driver.ConfigDriver.main(ConfigDriver.java:114)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.solrmarc.driver.Boot.invokeMain(Boot.java:201)
        at org.solrmarc.driver.Boot.main(Boot.java:74)
DEBUG [main] (BootableMain.java:117) - Adding directory: /tmp/vufind/local/import
DEBUG [main] (BootableMain.java:117) - Adding directory: /tmp/vufind/import
</pre>

**Comment by demiankatz** [comment]
Looks like the problem is in https://github.com/solrmarc/solrmarc/blob/master/src/org/solrmarc/driver/Boot.java somewhere; I'm out of time for today, but please let me know if you'd like me to spend more time investigating, and I may be able to find time to troubleshoot this further in a few days.

**Comment by demiankatz** [comment]
It's also problem that this is the direct culprit: https://github.com/solrmarc/solrmarc/blob/master/src/org/solrmarc/driver/BootableMain.java#L116 -- it's curious to me that the output only shows us adding two directories, yet lists a directory count of 3. Is a symlink somehow resolving as a list containing both versions of the path?

**Comment by demiankatz** [comment]
More information: I have received a report that the problem is specifically linked to the solrmarc.path setting in the import.properties file. If that points to a symbolic link, things break; if it points to a "real" path, things work. Perhaps some additional logic needs to be added to the configuration processing to dereference symbolic links.
